### PR TITLE
IT added

### PR DESCRIPTION
**Pull request by mariapoveda**
Added the ontology for the Issue Tracker domain

### CODE REVIEW

**Comment by mestebangutierrez** [comment]
Travis errors are due to a Travis issue.

**Comment by mestebangutierrez** [comment]
Why the publisher of the ontology is the _Center for Open Middleware_ instead of the _Smart Developer Hub_ project?

Also, `dcterms:publisher` has range `dcterms:Agent.`

**Comment by mestebangutierrez** [comment]
With regards to the license, `dcterms:license` has range `dcterms:LicenseDocument`, and the property _refines_  `dcterms:rights`, which has range `dcterms:RightsStatement`. So why do we need both?

**Comment by mariapoveda** [comment]
We use dcelements:rights, dcterms:rightsHolder and dcterms:license

**Pull request closed without merging**
